### ISSUE TITLE
SCOM Alerts tab doesn't work with PHP 7.4.6

### ISSUE THREAD

**Issue by mwaldmueller** [Thomas-Gelf/icingaweb2-module-eventtracker#30]
After updating from PHP 7.2.5 to PHP 7.4.6 the "SCOM Alerts" tab doesn't work any more, although pdo_dblib was adjusted. All other tabs work as expected.

![scom_alerts](https://user-images.githubusercontent.com/3973350/174536015-e9504b24-3a09-4147-9d02-1edb8db66655.png)

# Environment
Eventtracker: v0.9.0
PHP: 7.4.6

**Comment by Thomas-Gelf** [comment]
Please check your PHP INI files, pdlib.so must be loaded - the message shows, that it isn't. Also, please restart php-fpm (or your Apache server, in case you're running PHP as a module) when tweaking the PHP configuration. `php -m` shows loaded modules on CLI, a PHP file containing `<?php phpinfo();` would do a similar (better) job via web. Web and cli are using different configurations.

**Comment by mwaldmueller** [comment]
pdo_dblib is definitely loaded and works for other views (e.g. "Event Tracker"). Only "SCOM Alerts" doesn't recognise it. Here the output of phpinfo:
![Bildschirmfoto 2022-06-20 um 15 17 06](https://user-images.githubusercontent.com/3973350/174610521-7d02dec0-0ffa-4ad3-a0e8-d6ac24a9e8c0.png)

**Comment by Thomas-Gelf** [comment]
Strange. Btw, the Event Tracker view doesn't use an MSSQL connection - only the daemon does. The "SCOM Alerts" is a menu entry for debugging purposes only, this used to be an experiment for an upcoming dedicated SCOM module. Is the daemon successfully polling your SCOM DB?

**Comment by mwaldmueller** [comment]
No, the error message is still the same. That's why I opened this issue ;-)

**Comment by mwaldmueller** [comment]
I'm sorry, the view worked again after a few hours, but the customer didn't inform me. From my point of view you can revert the changes. Thanks for the effort!

**Comment by Thomas-Gelf** [comment]
Thanks for letting me know, I really was wondering how this could happen. Probably php-fpm hasn't been restarted, and/or that session has still been served from a former php-fpm-process. Anyway, that view was an experiment to prototype an upcoming dedicated SCOM-module. As its query doesn't match 100% what the daemon does internally, it's probably better not to show it at all.
